from enum import StrEnum


class RoleEnum(StrEnum):
    MASTER_ADMIN = "MASTER_ADMIN"
    BUSINESS_OWNER = "BUSINESS_OWNER"
    BUSINESS_ADMIN = "BUSINESS_ADMIN"
    BUSINESS_EMPLOYEE = "BUSINESS_EMPLOYEE"
